### ISSUE TITLE
Example does not work out of the box

### ISSUE THREAD

**Issue by paulalex** [sensson/docker-magento2#11]
Hi, on running the example it immediately fails to work on mac mojave.

`magento-frontend | Waiting on database connection..`

Similarly the cron container has the same issue. Can you confirm that the example still works?

A little digging and this seems to be the cause:

`root@5a55d523cd70:/var/www/html# mysqladmin ping -h"mysql"
mysqladmin: connect to server at 'mysql' failed
error: 'Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory'`

**Comment by paulalex** [comment]
I 'think' rolling back mysql to version 5 works rather than using latest.

**Comment by paulalex** [comment]
After all this and installing magento 2.2.7 into the src folder it still doesnt work. Has been running over 20 minutes and still gives same errors:

Error in cron container:
`
2019-03-04T23:11:00.928077800Z   [PDOException]
2019-03-04T23:11:00.928094400Z   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.store_group' doesn't exist
2019-03-04T23:11:00.928115300Z
2019-03-04T23:11:00.928135900Z
2019-03-04T23:11:00.928156200Z setup:di:compile
2019-03-04T23:11:00.928176400Z
`

Error in web server container:

`
2019-03-04T23:17:28.682373900Z
2019-03-04T23:17:28.843367700Z Installing schema...
`

**Comment by ju5t** [comment]
> I 'think' rolling back mysql to version 5 works rather than using latest.

I forgot to change this in the example. You're right, this should be MySQL 5 instead of latest. I don't believe Magento is ready for MySQL 8 yet.

> After all this and installing magento 2.2.7 into the src folder it still doesnt work.

The errors you're seeing are very hard to debug without more information.

I have upgraded Magento to 2.2.7 in our example and that works.

```
cd src && composer install && cd ..
docker-compose --build up
```

Can you try this?

I am on MacOS myself too, by the way.

**Comment by paulalex** [comment]
Thanks I will try this tonight! Will this work with magento 2.3?

**Comment by ju5t** [comment]
@paulalex I haven't tested 2.3. It could work, but I honestly don't know.

We're not using Magento ourselves anymore. It didn't fit our use case but we try to keep our open source projects on GitHub working. You're welcome to raise a PR to support 2.3 too, in case that's needed.

**Comment by paulalex** [comment]
@ju5t many thanks, I maye invest some time this evening getting this running with magento 2.3 and then raise a PR once happy. I am surprised it meets anyones use case.. this is my first venture into magento as I am a java dev, its not particularly nice to work with! 

Cheers
