### ISSUE TITLE
'sockets' extension missing on install magento 2.3.4

### ISSUE THREAD

**Issue by ghost** [sensson/docker-magento2#15]
I created a plain src from magento community 
```
composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition src
```

When I reach command: `bin/magento setup:install`

following error shows up 
```
In Installer.php line 521:
                                           
  Missing following extensions: 'sockets'  
```

can be fixed with `docker-php-ext-install sockets`

I think this php extension should be installed.

**Comment by ju5t** [comment]
Thanks for bringing this up. We're always open for pull requests. Feel free to add it.

**Comment by ghost** [comment]
Sure!
#17
